DROP TABLE IF EXISTS jedis;

CREATE TABLE jedis (
  id serial PRIMARY KEY,
  name varchar(50) NOT NULL,
  lightsaber_color varchar(50) NOT NULL,
  years_training integer NOT NULL,
  tempted_by_dark_side boolean NOT NULL,
  temptation varchar(50) NOT NULL
);

INSERT INTO jedis (name, lightsaber_color, years_training, tempted_by_dark_side, temptation) VALUES
  ('Sara Antilles', 'white', 14, FALSE, 'The LES'),
  ('Jason Tarkin', 'blue', 12, FALSE, 'beards'),
  ('Boyd Windu', 'gray', 15, FALSE, 'ECMAScript 6'),
  ('Chancellor Chan', 'purple', 18, FALSE, 'video games'),
  ('Pete-3P0', 'teal', 5, FALSE, 'proper electrical grounding'),
  ('Fatima Fortuna', 'green', 5, FALSE, 'Tupac vs. Biggie debates'),
  ('Noah FN-2187', 'red', 3, FALSE, 'photography'),
  ('Bo-Bi-Wan Kenobi', 'blue', 50, FALSE, 'fresh powdered snow'),
  ('Darth Carver','red',7,TRUE,'puppies'),
  ('Master Mytko', 'green', 14, FALSE, 'altoid mints'),
  ('Dennis the Hutt', 'red', 7, TRUE, 'japanese whiskey'),
  ('Dana Fett', 'orange', 14, FALSE, 'adobe creative suite'),
  ('John Beru', 'green', 8, FALSE, 'supercars'),
  ('Oola Holz', 'red', 19, TRUE, 'business'),
  ('Admiral Jaafari', 'blue', 10, FALSE, 'unit testing'),
  ('Amelia Kota', 'orange', 14, FALSE, 'slackbots'),
  ('Molly Kanata', 'red', 8, TRUE, 'fashion'),
  ('Christopher Revan', 'red', 2, TRUE, 'darts'),
  ('J-SN0', 'brown', 11, FALSE, 'VIM'),
  ('Dylan Skywalker', 'red', 6, TRUE, 'the perfect screenplay'),
  ('Elizabeth Radlein', 'white', 5, FALSE, 'privacy'),
  ('Nica Sidious', 'red', 19, TRUE, 'tarantulas'),
  ('Jango Yang', 'navy', 11, FALSE, 'type checking'),
  ('Ruth Amidala', 'green', 17, FALSE, 'good books'),
  ('Eric-47', 'purple',20, FALSE, 'cookies'),
  ('Josue Calrissian', 'brown',13, FALSE, 'wanderlust'),
  ('Jeselin Duo', 'green',18, FALSE, 'caps'),
  ('Leonel Dooku Jr.', 'purple', 18, FALSE, 'crew cuts'),
  ('Emperor Di Meglio', 'red',14, TRUE, 'motorcycles'),
  ('Diana Gunray', 'purple',9, FALSE, 'mischief'),
  ('Bran-Don Jinn', 'blue', 14, FALSE, 'milk and cookies'),
  ('Shawn Mothma', 'blue',14, FALSE, 'dota 2'),
  ('Motti L. Clair', 'pink', 13, FALSE, 'Magic'),
  ('Dan Darklighter', 'green', 20, FALSE, 'beer'),
  ('Chris Maul', 'red', 1, TRUE, 'Red Sox'),
  ('Esther Organa', 'blue',9, FALSE, 'homework bonuses'),
  ('Jared-88', 'purple', 3, FALSE, 'guitar solos'),
  ('Danielle Nunb', 'white', 5, FALSE, 'travel'),
  ('Angela Solo', 'red',10, TRUE, 'star wars'),
  ('Nicolai Dameron', 'green', 18, FALSE, 'business'),
  ('General Rozova', 'gray', 12, FALSE, 'parallax scrolling'),
  ('Darth Savage', 'red', 6, TRUE, 'photography'),
  ('Alexander Sidious', 'red', 19, TRUE, 'ruby'),
  ('Kyle Katarn', 'maroon',7, FALSE, 'photography');
